// Generated by @monstermann/barrels
/* eslint-disable */
/* prettier-ignore */
// dprint-ignore-file
// biome-ignore lint: disable

import { aliases } from "./aliases.js";
import { isAlt } from "./isAlt.js";
import { isCtrl } from "./isCtrl.js";
import { isMeta } from "./isMeta.js";
import { isModifier } from "./isModifier.js";
import { isPlain } from "./isPlain.js";
import { isShift } from "./isShift.js";
import { isSpecial } from "./isSpecial.js";
import { modifiers } from "./modifiers.js";
import { resolve } from "./resolve.js";
import { special } from "./special.js";

declare namespace Key {
    export {
        aliases,
        isAlt,
        isCtrl,
        isMeta,
        isModifier,
        isPlain,
        isShift,
        isSpecial,
        modifiers,
        resolve,
        special,
    }
}

export {
    Key,
}
