// Generated by @monstermann/barrels
/* eslint-disable */
/* prettier-ignore */
// dprint-ignore-file
// biome-ignore lint: disable

import { bind } from "./bind.js";
import { bindings } from "./bindings.js";
import { evt } from "./evt.js";
import { isExactMatch } from "./isExactMatch.js";
import { isPartialMatch } from "./isPartialMatch.js";
import { normalize } from "./normalize.js";
import { serialize } from "./serialize.js";
import { unbind } from "./unbind.js";
import { vim } from "./vim.js";
import { vsc } from "./vsc.js";

declare namespace Hotkeys {
    export {
        bind,
        bindings,
        evt,
        isExactMatch,
        isPartialMatch,
        normalize,
        serialize,
        unbind,
        vim,
        vsc,
    }
}

export {
    Hotkeys,
}
